name: snakespeare
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - graphviz=2.38.0
  - python=3.7.6
  - r-base=3.6.3
  - r-dplyr=0.8.3
  - r-ggplot2=3.2.0
  - r-readr=1.3.1
  - r-tidyr=1.1.3
  - r-systemfonts=0.1.1
  - r-yaml=2.2.1
  - snakemake=5.4.5
