name: snakespeare
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - graphviz
  - python=3.7.6
  - r-base=3.6.3
  - r-dplyr
  - r-ggplot2
  - r-readr
  - r-tidyr
  - r-systemfonts
  - r-yaml
  - snakemake=5.4.5
